### ISSUE TITLE
it is possible to have a responsive design with KnowcodeXML

### ISSUE THREAD

**Issue by nosadaniel** [TotalCross/KnowCodeXML#23]

**Comment by nosadaniel** [comment]
Hello,
Please I want to know if it possible  for knowcode-xml  for mobile irrespective of the mobile screen size.

**Comment by nosadaniel** [comment]
for mobile phone

**Comment by brunoamuniz** [comment]
Hello @nosadaniel, YES! TotalCross is fully responsive, even if you create a ConstraintLayout to use with KnowCode, it should adjust to different screen sizes and resolutions
